### PR TITLE
Cloned Velusia to Rentor for customized class sample & integer TKey

### PR DESCRIPTION
**Pull request by mlhDevelopment**
Create a sample to troubleshoot customized Application, Token, Scope, and Authorization classes, and the primary key would be an integer. This sample is the same as Velusia but with only those pieces updated.

### CODE REVIEW

**Comment by kevinchalet** [comment]
Thanks for your PR 👍🏻 

Maintaining samples has a cost and it's not clear to me whether having a dedicated sample for a such a specific scenario makes sense. Instead, could that be covered by a dedicated page in the documentation?

**Comment by mlhDevelopment** [comment]
Yes, not a problem. I made this mostly for my own research and since it was basically complete sent it as a PR. No need for white elephants, I agree.

**Comment by kevinchalet** [comment]
I still think it would be valuable to have that somewhere. https://github.com/openiddict/openiddict-documentation/issues/9 tracks adding some documentation (likely a single page) for this scenario. Would you be interested in taking it? 😃

**Comment by mlhDevelopment** [comment]
Yes, I'll give it a shot but may be slow.

**Pull request closed without merging**
