### PR TITLE
Update Velusia user account and manage interface with Identity UI RCL

### PR DESCRIPTION
**Pull request by jeremycook**
Velusia.Server project was recreated from VS 2019 with the .NET 5 MVC template and then modified based on the existing Velusia.Server project.

I did a couple extra things that strictly are not needed because I originally thought this would result in a new sample project. They were:

* Enabled Nullable for the entire Velusia.Server project to go along with where Microsoft seems to be asking us developers to go. I adjusted some code accordingly: adding question and exclamation marks where needed, and adding one null coalesce exception in the Authorization controller.
* Added SmtpClientEmailSender and options with a tip for using a development SMTP server.
* Doing the above allowed me to require confirmed account with `AddIdentity<ApplicationUser, IdentityRole>(options => options.SignIn.RequireConfirmedAccount = true)` since this is how it was scaffolded by Microsoft's template. Not strictly needed for a sample but I've always found that with an IdP I always want to verify the email address because clients tend to implicitly trust the email address it provides. So I went along with what was scaffolded.

### CODE REVIEW

**Comment by kevinchalet** [comment]
Thanks for your PR!

> Enabled Nullable for the entire Velusia.Server project to go along with where Microsoft seems to be asking us developers to go. I adjusted some code accordingly: adding question and exclamation marks where needed, and adding one null coalesce exception in the Authorization controller.

That's nice! That said, we should probably do that in a separate PR and update all the samples at the same time for consistency.

> Added SmtpClientEmailSender and options with a tip for using a development SMTP server.

I get the intent, but as it's exclusively a user authentication/ASP.NET Core Identity concern, I'm a bit reluctant to have it in the OpenIddict samples, that should focus on the OIDC part (it's also code we have to maintain, and these things seem to change from time to time... 😅).

> Doing the above allowed me to require confirmed account with `AddIdentity<ApplicationUser, IdentityRole>(options => options.SignIn.RequireConfirmedAccount = true)` since this is how it was scaffolded by Microsoft's template. Not strictly needed for a sample but I've always found that with an IdP I always want to verify the email address because clients tend to implicitly trust the email address it provides. So I went along with what was scaffolded.

How good/bad is the user experience when enabling this option? It's enabled in the Balosar sample and it makes the sample harder to use with the fake "confirm your email" page. I'm wondering if we shouldn't leave it disabled and add a tiny note in the `services.Configure<IdentityOptions>(options => ...)` lambda instead.

**Comment by jeremycook** [comment]
1. I removed the Nullable attribute.
2. I removed all IEmailSender stuff except for a note in Startup.cs and added the new shortcut URL while at it. I removed it because if you do not register an IEmailSender service you'll get an instructional page if you enable RequireConfirmedAccount. Which I thought would be helpful for the adventurous.
3. I set RequireConfirmedAccount to false with a note. The flow is passable with it enabled, you are presented the aforementioned instructional page, but it loses the "/connect/..." returnUrl which breaks the user's flow for the purpose of demoing OpenIddict. So setting it to false with a note seemed like an acceptable middle ground.

**Comment by kevinchalet** [comment]
Thanks for the changes!

Sadly, it looks like I broke your PR with my Integrated Windows Authentication sample, sorry for that.
Could you please rebase your branch on top of `upstream/dev`?

Thanks!

**Comment by jeremycook** [comment]
Rebased

**Comment by kevinchalet** [comment]
Thanks for your contribution! 👏🏻

**Pull request merged**
